### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by dirkk0** [deepstreamIO/ds-tutorial-tanks#5]
Hi,

  I successfully started the server (see #4 ) and I see that the clients connect. I also see that there are no errors on the console.

I see the terrain but that's pretty much it - how do you play?

Best,
  Dirk

**Comment by yasserf** [comment]
Hey,

Good point! This was initially build to run against some servers in the cloud which is why the readme didn't have the stuff.

This game uses a centralized state maintained a game-server client. You just need to run that too and it will work!

**Comment by dirkk0** [comment]
ah, ok. works like a charm.

I just tried to add the pull request for the package.json, but you were faster. :-)
