### ISSUE TITLE
0.0.0.0

### ISSUE THREAD

**Issue by dirkk0** [deepstreamIO/ds-tutorial-tanks#6]
How would I configure deepstream (i.e. this line: https://github.com/deepstreamIO/ds-tutorial-tanks/blob/master/browser/src/js/main.js#l12 ) that it accepts connections from everywhere?

I tried '0.0.0.0' but that didn't work.

**Comment by yasserf** [comment]
0.0.0.0 should work, where you hosting it?

**Comment by WolframHempel** [comment]
That line is on the client. You would need to tell your server to listen to '0.0.0.0' here https://github.com/deepstreamIO/ds-tutorial-tanks/blob/master/ds-server/start.js#L5

**Comment by dirkk0** [comment]
Yes, but that line on the server already there, so the servers do listen on 0.0.0.0.
But I needed to change the 'localhost' line on the client to the local IP of the PC to be able to access it from another PC. I thought there could be a better way, that works right away.

**Comment by WolframHempel** [comment]
I'm afraid that's just how networks work. Your client needs to know where it needs to connect to.

**Comment by dirkk0** [comment]
I am quite sure there is a way and it looks similar to this:
`var host = window.document.location.host.replace(/:.*/, '');`

I think this can replace the 'localhost' entry at line 12, but I can't test it before tonight.

**Comment by WolframHempel** [comment]
yup, provided that your http server and deepstream run on the same domain and you're not using the client in nodeJs. If you'd like to always point your client to a deepstream server running on a different port on the same host, you could of course do that (even easier, `document.location.hostname + ':6020'` )

**Comment by dirkk0** [comment]
Good points!

For the sake of ease of running this tutorial code, I would recommend doing the .hostname thing.
